// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWHjp026aIeKv2Gnf9KWJCyCr0ghXc8fk',
    appId: '1:976172192756:web:548285a3134408f18e1fa1',
    messagingSenderId: '976172192756',
    projectId: 'dtlive-12784',
    authDomain: 'dtlive-12784.firebaseapp.com',
    storageBucket: 'dtlive-12784.firebasestorage.app',
    measurementId: 'G-ZNNGBQXPH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcObQ6BE_DG5HHRxRr8UTdJSLAtlBuNEg',
    appId: '1:976172192756:android:c3692a8a3c3eabea8e1fa1',
    messagingSenderId: '976172192756',
    projectId: 'dtlive-12784',
    storageBucket: 'dtlive-12784.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Km3XO8A2LdAYO7-FC9blnxBbhHA3Bps',
    appId: '1:976172192756:ios:aba072dc0c15c34b8e1fa1',
    messagingSenderId: '976172192756',
    projectId: 'dtlive-12784',
    storageBucket: 'dtlive-12784.firebasestorage.app',
    iosBundleId: 'com.javstory.prjkt',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Km3XO8A2LdAYO7-FC9blnxBbhHA3Bps',
    appId: '1:976172192756:ios:aba072dc0c15c34b8e1fa1',
    messagingSenderId: '976172192756',
    projectId: 'dtlive-12784',
    storageBucket: 'dtlive-12784.firebasestorage.app',
    iosBundleId: 'com.javstory.prjkt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWHjp026aIeKv2Gnf9KWJCyCr0ghXc8fk',
    appId: '1:976172192756:web:7185bba6af92e7248e1fa1',
    messagingSenderId: '976172192756',
    projectId: 'dtlive-12784',
    authDomain: 'dtlive-12784.firebaseapp.com',
    storageBucket: 'dtlive-12784.firebasestorage.app',
    measurementId: 'G-407LYLFC85',
  );
}
